# -*- coding: utf-8 -*-
"""LVADSUSR154_Hareesh_Kumaar_GJ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3YUx0R2V3Zeh1wr9Zh7ujb9pGcAFnD7

LAB 1
"""

#1
length = float(input("Enter the length of the area in metres "))
width = float(input("Enter the width of the area in metres "))
area = length*width
if area < 500:
  print(f"The area is {area} and categorized as small space")
elif area <=1000:
  print(f"The area is {area} and categorized as medium space")
else:
  print(f"The area is {area} and categorized as large space")

#2
height = float(input("Enter the height : "))
weight = float(input("Enter the weight : "))
bmi = weight / (height**2)
if bmi < 18:
  print(f"The person is underweight with a bmi of {bmi}, eat more proteins and carbs")
elif bmi < 24:
  print(f"The person is in good shape with a bmi of {bmi}, stay fit!")
else:
  print(f"The person is overweight with a bmi of {bmi}, have a balanced diet and workout regularly")

#3
grade = {"Hareesh":{"Maths:95","Physics:80","English:92"},"Kumaar":{"Maths:88","Physics:70","English:95"}}
for k,v in grade.items():
  print(k)
  for i,j in v.items():
    print(i," ",j)

def add():
  pass
def retrieve():
  pass
def update():
  pass
def print_grade():
  for i in grade:
    for k,v in i:
      print(k," ", v)

#while(True):
#  inp = int(input("Enter choice 1 - Add 2 - Update  3 - Retrieve 4 - Print"))
#  if inp ==1:
#   add()
#  elif inp ==2:
#    update()
#  elif inp ==3:
#    retrieve()
#  elif inp ==4:
#    print_grade()
#  else:
#    break

"""LAB 2"""

#4
age = int(input("Enter your age : "))
if age<12:
  print("You come under Children category")
elif age <20:
  print("You come under Teen category")
elif age < 40:
  print("You come under Adult category")
else:
  print("You come under Senior category")

#5
subscriber_id = [202,107,320,500,343,219,222]
for i in subscriber_id:
  if i%2 ==0:
    print(i)

#6
password = "LVADSUSR154"
while(True):
  user_pwd = input("Enter password : ")
  if user_pwd == password:
    print("Login Success")
    break
  else:
    print("Wrong password. Please try again")

"""LAB 3"""

#7
def avg_feedback_calculation(a):
  sum = 0;
  for i in a:
    sum += i
  avg = sum / len(a)
  return avg

feedback = [8,3,9,10,2,7,3]
average = avg_feedback_calculation(feedback)
print("Average :",average)

if average < 5:
  print("Need improvement")
elif average <=7.5:
  print("Good job")
else:
  print("Excellent")

#8
def vowel_count(a):
  count = 0
  for i in range(len(s)):
    if(a[i]=='a' or a[i]=='e' or a[i]=='i' or a[i]=='o' or a[i]=='u' ):
      count+=1
  print("Number of vowels : ",count)
s = input("Enter Comment : ")
vowel_count(s)

#9
import datetime
dt = datetime.datetime.now()
print(dt)

"""LAB 4"""

#10
try:
  balance = 1000
  inp = int(input("Enter amount to withdraw : "))
  balance =balance-inp

except ValueError as e:
  print(e)

#11
t=True
while(t):
  try:
    inp = int(input("Enter integer data "))
    print("Data in correct format")
  except ValueError as e:
    print("Data not in correct format")
    t=False

#12
t=True
while(t):
  try:
    inp1 = int(input("Enter 1st integer "))
    inp2 = int(input("Enter 2nd integer "))
    print(inp1/inp2)
  except ZeroDivisionError as e:
    print("Denominator shouldn't be zero")
    t=False

"""LAB 5"""

#13
while(True):
  with open("Logfile.txt","a") as file:
    inp = input("Enter log details: ")
    file.write(inp)
    c = int(input("Do you want to continue. Press 1 for yes and 0 for no"))
    if c == 0:
      break

file_r = open("Logfile.txt","r")
print(file_r.read())

#14
file_r = open("Logfile.txt","r")
try:
  print(file_r.read())
except FileNotFoundError as e:
  print("File is not found")
finally:
  file_r.close()

#15
while(True):
  with open("Logfile.txt","a") as file:
    inp = input("Enter log details: ")
    file.writelines(inp)
    c = int(input("Do you want to continue. Press 1 for yes and 0 for no"))
    if c == 0:
      break

file_r = open("Logfile.txt","r")
lines = file_r.readlines()
for line in lines:
  print(line)